from pathlib import Path
from typing import BinaryIO, Protocol


class StorageBackend(Protocol):
    def put(self, key: str, stream: BinaryIO, content_type: str) -> None: ...

    def download_to(self, key: str, target: Path) -> None: ...

    def delete(self, key: str) -> None: ...

    def move(self, source_key: str, target_key: str) -> None: ...

    def presigned_get_url(self, key: str, expires_seconds: int) -> str: ...
